version: 2

defaults: &defaults
  docker:
  - image: circleci/android:api-28

  environment:
    JVM_OPTS: -Xmx3200m

jobs:

  build:
    working_directory: ~/code

    <<: *defaults

    steps:
    - checkout

    - restore_cache:
        key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}

    - run:
        name: Download configuration files
        command: ./ci_config/fetch_config.sh

    - run:
        name: Download Dependencies
        command: ./gradlew androidDependencies

    - run:
        name: Build Project
        command: ./gradlew build --scan --exclude-task test

    - save_cache:
        paths:
        - ~/.gradle
        key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}

    - run:
        name: Run Tests
        command: ./gradlew lint test

    - store_artifacts:
        path: app/build/reports
        destination: reports

    - store_test_results:
        path: app/build/test-results