version: 2

defaults: &defaults
  working_directory: ~/code

  docker:
    - image: circleci/android:api-30-node

  environment:
    JVM_OPTS: -Xmx3200m
    GRADLE_OPTS: -Dorg.gradle.daemon=false

cache_key: &cache_key
  key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

grab_configuration_files: &grab_configuration_files
  name: Download configuration files
  command: sudo chmod +x ./ci-config/fetch-config.sh && ./ci-config/fetch-config.sh

jobs:

  debug-build:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          <<: *cache_key

      - run:
          <<: *grab_configuration_files

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - run:
          name: Build Project
          command: ./gradlew assembleDebug --scan --rerun-tasks

      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum "app/build.gradle.kts" }}

      - store_artifacts:
          path: app/build/reports
          destination: reports

      - store_test_results:
          path: app/test/test-results

  unit-tests:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          <<: *cache_key

      - run:
          <<: *grab_configuration_files

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - run:
          name: Run Unit Tests
          command: ./gradlew testDebugUnitTestCoverage --scan --rerun-tasks

      - run:
          name: Upload code coverage report
          command: bash <(curl -s https://codecov.io/bash) -f "*.xml"

      - run:
          name: Run detekt
          command: ./gradlew detekt

#      - run:
#          name: Clear daemon cache
#          command: rm -fr ~/.gradle/daemon/

      - store_test_results:
          path: app/test/test-results

  lint:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          <<: *cache_key

      - run:
          <<: *grab_configuration_files

      - run:
          name: Run detekt
          command: ./gradlew detekt

      - run:
          name: Run Android lint
          command: ./gradlew lintDebug

      - store_artifacts:
          path: reports/
          destination: reports

      - store_artifacts:
          path: reports/detekt
          destination: reports/detekt

workflows:
  version: 2

  develop:
    jobs:
      - unit-tests

#      - lint:
#          requires:
#            - unit-tests